## What We Looked At Last Time
* Our last module address **Object-Oriented Programming** in the context of Python programming.
* Along the way, we addressed the creation of **classes** and _methods_ for those classes.
* Lastly, we briefly addressed the concept of **inheritance** in Python.

## What We'll Look At In This Module
* We'll introduce **NumPy arrays**, which are pivotal to _efficient computation_ in Python.
* We'll look at ways to measure time (including the _elapsing of time_) in Python.

# Arrays-Oriented Programming 

### **NumPy** (**Numerical Python**) Library
* First appeared in 2006 and is the **preferred Python array implementation**.
* High-performance, richly functional **_n_-dimensional array** type called **`ndarray`**. 
* **Written in C** and **up to 100 times faster than lists**.
* Critical in big-data processing, AI applications and much more. 
* According to `libraries.io`, **over 450 Python libraries depend on NumPy**. 
* Many popular data science libraries such as Pandas, SciPy (Scientific Python) and Keras (for deep learning) are built on or depend on NumPy. 

## Creating `array`s from Existing Data 
* NumPy arrays are often generated from existing data structures using the **`array`** function.  
* The argument must be an `array` or other iterable.
* The result is a **new** `array` containing the argument’s elements

In [1]:
import numpy as np

In [2]:
myList = [2, 3, 5, 7, 11] 
myArray = np.array([2, 3, 5, 7, 11])
print(type(myList))
print(type(myArray))
print(myList)
print(myArray) #Note the print representation lacks commas.

<class 'list'>
<class 'numpy.ndarray'>
[2, 3, 5, 7, 11]
[ 2  3  5  7 11]


## Array Basics
* 2+ dimensional lists can also converted quickly to array-format using the `array` function.
* For performance reasons, NumPy is written in the C programming language and uses C-based data types
    * This means that matching data-types will appear differently (ex: different significant digits for decimals) when stored in a NumPy array. 
    * [Other NumPy types can be found here.](https://docs.scipy.org/doc/numpy/user/basics.types.html)
    * Structured arrays permit more flexible array representations, but are not dealt with in this session.


In [5]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(integers)
print(floats)

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4]


In [6]:
floats[0] = 'Hello'

ValueError: could not convert string to float: 'Hello'

### Determining `array` Properties
* Using the Python function `type` will not display the data type stored in an array -- instead, the `.dtype` method must be called on the array. 
* `ndim` contains an `array`’s number of dimensions 
* `shape` contains a _tuple_ specifying an `array`’s dimensions

In [7]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
print(type(integers))
print(integers.dtype)
print(floats.dtype)

<class 'numpy.ndarray'>
int64
float64


In [9]:
print(integers)
print(floats)

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4]


In [8]:
print(integers.ndim)
print(floats.ndim)
print(integers.shape)
print(floats.shape) #Remember that 1d tuples always include a comma for distinction!

2
1
(2, 3)
(5,)


### Iterating through a Multidimensional `array`’s Elements
* Arrays are generally iterated through using `for` or `while` loops.
* `.flat` will provide a flattened representation of an array.
    * For a 2-d array, the 2nd "row" will be appended to the first, followed by the 3rd, etc.
    * For larger arrays, concatenation takes place using a "right-to-left" priority by dimension.
    

In [12]:
integers = np.array([[1, 2, 3], [4, 5, 6],[7,8,9],[10,11,12]])

In [13]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print() 

1  2  3  
4  5  6  
7  8  9  
10  11  12  


In [14]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  7  8  9  10  11  12  

# Filling `array`s with Specific Values
* Functions `zeros` or  `ones` will create an array with a shape corresponding to a given tuple (or 1-d array if a single number is provided) 
* `full` creates an `array` containing a value specified as a second argument.
* Only integers are permitted for the array shape parameter, but any numeric type is suitable for `full`'s second parameter.

In [18]:
arr0s = np.zeros(5)
arr1s = np.ones((3,4))
arrvals = np.full((2,3),5.5)
print('.zeros:')
print(arr0s)
print('.ones:')
print(arr1s)
print('.full:')
print(arrvals)

.zeros:
[0. 0. 0. 0. 0.]
.ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
.full:
[[5.5 5.5 5.5]
 [5.5 5.5 5.5]]


# Creating `array`s from Ranges 
* NumPy provides optimized functions for creating `array`s from ranges
* The `arange` method has similar operation to `range`, but produces a 1-dimensional array.
* `linspace` creates a 1-dimensional array of floating-point values from the 1st argument to the 2nd, uniformly spaced to represent a number of values by the 3rd argument.
    * Unlike `range` or `arange`, both starting and ending points _are included_ when `linspace` is used.

In [19]:
print(np.arange(5))
print(np.arange(5,10))
print(np.arange(10,1,-2))

[0 1 2 3 4]
[5 6 7 8 9]
[10  8  6  4  2]


In [20]:
print(np.linspace(0.0, 1.0, num=5))

[0.   0.25 0.5  0.75 1.  ]


### Reshaping an `array` 
* The `array` method **`reshape`** transforms an array into different number of dimensions
* The new shape must have the **same** number of elements as the original

In [21]:
print(np.arange(1,13))
print(np.arange(1,13).reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Large `array`s and Display 
* When displaying an `array`, if there are 1000 items or more, NumPy drops the middle rows, columns or both from the output

In [22]:
import numpy as np
print(np.arange(1, 100001).reshape(4, 25000))

[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]


In [23]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

## Arrays and Placeholder Values
One way to produce an array with desired values using the NumPy library involves a two-step process as follows:
1. We create an array with the dimensions that we wish to use with starting placeholder values (ex: 0 or 1 are typical)
2. We then rely on a series of **for loops** to generate _actual_ values relevant to the array and plug them into the correct indices

In [24]:
#Ex: We can create a 2-dimensional array of 1s and then use a pair of for loops to produce a sum of the row and column index
maxrows = 10
maxcols = 5
myarray = np.ones((maxrows,maxcols))
for row in range(maxrows):
    for col in range(maxcols):
        myarray[row,col] = row + col
print(myarray)

[[ 0.  1.  2.  3.  4.]
 [ 1.  2.  3.  4.  5.]
 [ 2.  3.  4.  5.  6.]
 [ 3.  4.  5.  6.  7.]
 [ 4.  5.  6.  7.  8.]
 [ 5.  6.  7.  8.  9.]
 [ 6.  7.  8.  9. 10.]
 [ 7.  8.  9. 10. 11.]
 [ 8.  9. 10. 11. 12.]
 [ 9. 10. 11. 12. 13.]]


## Practice 1: Creating a Few Tables Arrays and Placeholder Values
Using the method above for generating an initial array of placeholder values and then filling it in with correct values, you are to accomplish the following tasks:
i. Allow a user to input a number **n**, and then generate a _nXn times table_. <br>
ii. Allow a user to input a number **n** and then generate a _nXn identity matrix_.  Note that this one only requires one loop to produce.

## List vs. `array` Performance: Introducing `datetime` 
* Most `array` operations execute **significantly** faster than corresponding list operations
* The `datetime` library includes all sorts of functionality related to measuring, displaying, and converting absolute times and durations.
* We can create an object that provides a microsecond-precise measurement of the _current_ time using `datetime.now()`


In [28]:
from datetime import datetime
from time import sleep
start=datetime.now()
sleep(10)
end=datetime.now()
print((end-start).total_seconds())
print(type(end-start))

10.008124
<class 'datetime.timedelta'>


In [48]:
from datetime import datetime
print(datetime.now())
print(type(datetime.now()))

2025-04-04 09:24:59.991724
<class 'datetime.datetime'>


### Using `datetime` to Measure Durations. 
* If we determine the time _before_ and _after_ an operation(s) we're interested in, we can measure the corresponding execution time.
* The object return by an arithmetic operation (ex: subtraction) using `datetime` objects is a `timedelta`, which measures duration.
* The `timedelta` class has a method `total_seconds()` which returns a string representation of the duration in seconds.

In [49]:
from time import sleep
start=datetime.now()
sleep(1)
end=datetime.now()
print((end-start).total_seconds())
print(type(end-start))

1.001164
<class 'datetime.timedelta'>


### Timing the Creation of a List and an Array Containing Results of 6,000,000 Die Rolls 
* We will use the `timedelta` approach from above to compute the time taken to generate a list with 6 million die rolls, and then an array with 6-million die rolls.
    * The list generation will use standard list comprehension.
    * The array will be built using the NumPy `random.randint` function, which fills a 1-dimensional array with random integers from the first parameter to the second-parameter (not inclusive), a total number of times equal to the third parameter.

In [52]:
import random
start=datetime.now()
randrolls=[random.randrange(1,7) for i in range(0,6_000_000)]
end=datetime.now()
print((end-start).total_seconds())

2.763517


In [55]:
start=datetime.now()
rolls_array = np.random.randint(1, 7, 6_000_000)
end=datetime.now()
print((end-start).total_seconds())

0.09818


### 60,000,000 and 600,000,000 Die Rolls  
* Generating a list of 60 million or 600 million die rolls would be quite slow.
* Both are quite fast with NumPy generation, however.

In [56]:
start=datetime.now()
rolls_array = np.random.randint(1, 7, 60_000_000)
end=datetime.now()
print((end-start).total_seconds())

0.718865


In [57]:
start=datetime.now()
rolls_array = np.random.randint(1, 7, 600_000_000)
end=datetime.now()
print((end-start).total_seconds())

6.86574


# `array` Operators
* `array` operators perform operations on **entire `array`s**. 
* We can perform arithmetic **between `array`s and scalar numeric values**, and **between `array`s of the same shape**.

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1, 6)
print(numbers)
print(numbers*2)
print(numbers**3)

[1 2 3 4 5]
[ 2  4  6  8 10]
[  1   8  27  64 125]


In [3]:
numbers += 10 #We can also use standard assignment operators with arrays.
print(numbers)

[11 12 13 14 15]


### Broadcasting 
* Arithmetic operations require as operands two `array`s of the **same size and shape**. 
* **`numbers * 2`** is equivalent to **`numbers * [2, 2, 2, 2, 2]`** for a 5-element array.
* Applying the operation to every element is called **broadcasting**. 


In [4]:
numbers2 = np.linspace(1.1, 5.5, 5)
numbers3 = [10,10,10,10,10]
print(numbers2*10)
print(numbers2*numbers3)

[11. 22. 33. 44. 55.]
[11. 22. 33. 44. 55.]


## Comparing `array`s
* We can compare `array`s with individual values and with other `array`s
* Comparisons are performed **element-wise**
* The result is an `array` of Boolean values in which each element’s `True` or `False` value indicates the comparison result

In [5]:
print(numbers)
print(numbers2)
print(numbers>=13)
print(numbers2>=13)


[11 12 13 14 15]
[1.1 2.2 3.3 4.4 5.5]
[False False  True  True  True]
[False False False False False]


In [6]:
print(numbers2 < numbers)
print(numbers == numbers)

[ True  True  True  True  True]
[ True  True  True  True  True]


## NumPy Calculation Methods
* Many calculations are applicable regardless of the number of elements, and thus can be used on arrays of any shape.
* Consider an `array` representing four students’ grades on three exams: we can compute various information to summarize the data (AKA programming **reductions**).
* The most common methods are **`sum`**, **`min`**, **`max`**, **`mean`**, **`std`** (standard deviation) and **`var`** (variance)
* [Other Numpy `array` Calculation Methods](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

In [7]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])
print(grades.sum())
print(grades.min())
print(grades.mean())
print(grades.std())


1054
70
87.83333333333333
8.792357792739987


## Calculations by Row Or Column
* You can perform calculations by column or row (or other dimensions in arrays with more than two dimensions)
* Each 2D+ array has [**one axis per dimension**](https://docs.scipy.org/doc/numpy-1.16.0/glossary.html)
* In a 2D array, **`axis=0`** indicates calculations should be **column-by-column**, while **`axis=1`** indicates calculations should be **row-by-row** 

In [8]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])
print(grades)
print(grades.max(axis=0)) #highest grade per exam
print(grades.mean(axis=1)) #student averages

[[ 87  96  70]
 [100  87  90]
 [ 94  77  90]
 [100  81  82]]
[100  96  90]
[84.33333333 92.33333333 87.         87.66666667]


# Universal Functions
* Standalone [**universal functions** (**ufuncs**)](https://docs.scipy.org/doc/numpy/reference/ufuncs.html) perform **element-wise operations** using one or two `array` or array-like arguments (like lists)
* Each returns a **new `array`** containing the results
* Some ufuncs are called implicitly when you use `array` operators like `+` and `*`

In [9]:
numbers = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(numbers))
print(np.log2(numbers))


[1. 2. 3. 4. 5. 6.]
[0.         2.         3.169925   4.         4.64385619 5.169925  ]


## Practice 2: Investigate Some Time-Related Tasks
i. Use the datetime library to generate a list of every Friday <br>
ii. Investigate and display a **user-friendly calendar** in Python (hint: Python has a _calendar_ library)

In [10]:
import datetime

def get_all_fridays(year):
    fridays = []
    date = datetime.date(year, 1, 1)
    while date.year == year:
        if date.weekday() == 4:
            fridays.append(date)
        date += datetime.timedelta(days=1)
    return fridays

for friday in get_all_fridays(2025):
    print(friday)

2025-01-03
2025-01-10
2025-01-17
2025-01-24
2025-01-31
2025-02-07
2025-02-14
2025-02-21
2025-02-28
2025-03-07
2025-03-14
2025-03-21
2025-03-28
2025-04-04
2025-04-11
2025-04-18
2025-04-25
2025-05-02
2025-05-09
2025-05-16
2025-05-23
2025-05-30
2025-06-06
2025-06-13
2025-06-20
2025-06-27
2025-07-04
2025-07-11
2025-07-18
2025-07-25
2025-08-01
2025-08-08
2025-08-15
2025-08-22
2025-08-29
2025-09-05
2025-09-12
2025-09-19
2025-09-26
2025-10-03
2025-10-10
2025-10-17
2025-10-24
2025-10-31
2025-11-07
2025-11-14
2025-11-21
2025-11-28
2025-12-05
2025-12-12
2025-12-19
2025-12-26
